export const resource = {
  otpDialog: {
    phoneVerification: 'Phone Verification',
    otpMessage: 'We have sent an OTP to your mobile number',
    changePhoneNumber: 'Change Phone Number',
    otpNotReceivedMessage: `Didn't got OTP. Resend in ? sec`,
    submit: 'Submit',
    wrongOTP: 'Wrong OTP',
    resendOtp: 'Resend OTP',
    or: 'or'
  },
  admin: {
    administration: 'Administration',
    admin: 'Administration',
    users: 'Users',
    'product-view': 'Product View',
    products: 'Products',
    socialMedias: 'Social Medias',
    'social-medias': 'Social Medias',
    sellers: 'Sellers',
    categories: 'Categories',
    orders: 'Orders',
    reviews: 'Reviews',
    socialMedia: {
      name: 'Name',
      url: 'Url',
      enabled: 'Enabled',
      cancel: 'Cancel',
      save: 'Save',
      addNew: '+ Add New',
      delete: 'Delete'
    },
    category: {
      name: 'Name',
      description: 'Description',
      parent: 'Parent',
      hierarchy: 'Hierarchy',
      hierarchyName: 'Hierarchy Name',
      enabled: 'Enabled',
      cancel: 'Cancel',
      save: 'Save',
      addNew: '+ Add New',
      delete: 'Delete'
    },
    seller: {
      name: 'Name',
      description: 'Description',
      storeName: 'Store Name',
      phoneNumber: 'Phone Number',
      enabled: 'Enabled',
      emailAddress: 'Email Address'
    },
    user: {
      name: 'Name',
      phoneNumber: 'Phone Number',
      enabled: 'Enabled',
      emailAddress: 'Email Address'
    },
    product: {
      name: 'Name',
      commonName: 'Common Name',
      description: 'Description',
      tags: 'Tags',
      locationTags: 'Location Tags',
      sku: 'Sku',
      sellerId: 'Seller Id',
      seller: 'Seller',
      category: 'Category',
      enabled: 'Enabled'
    }
  },
  registrationDialogContent: {
    createNewAccount: 'Create New Account',
    name: 'Name*',
    storeName: 'Store Name*',
    phoneNumber: 'Phone Number*',
    emailAddress: 'Email Address*',
    password: 'Password*',
    confirmPassword: 'Conform Password*',
    countryCode: '+91',
    createAccount: 'Create Account',
    validation: {
      nameIsRequired: 'Name is Required',
      nameMinLength: 'Name must be of at least 2 characters long',
      emailAddress: 'Please Enter a Valid Email Address',
      phoneNumber: 'Phone Number should be of length equal to 10',
      passwordIsRequired: 'Password is Required',
      passwordMinLength: 'Password must be atleast 8 characters long',
      passwordMaxLength: 'Password length must not exceeds 16 characters',
      passwordCriteria:
        'Must Contain 8 Characters, One Lowercase, One Number and one special case Character(@$!%*#?&_)',
      confirmNewPassword: 'Please confirm your password',
      confirmPasswordNotMatch: 'Passwords does not matches',
      match: 'Match'
    },
    or: 'Or',
    withGoogle: 'Continue With Google',
    withFacebook: 'Continue With Facebook',
    notice: `By clicking Create Account or Continue with Google, or Facebook you agree to our's Terms of Use & Privacy Policy. We may send you communications. We'll never post without your permission.`
  },
  createNewPasswordDialog: {
    submit: 'Submit',
    createNewPassword: 'Create New Password',
    enterNewPassword: 'Enter New Password',
    confirmNewPassword: 'Confirm New Password'
  },
  resetPassword: {
    resetPassword: 'Reset Password',
    phoneNumber: 'Enter your Phone Number',
    emailAddress: 'Email Address',
    invalidEmail: 'Invalid Email Address',
    invalidPhone: 'Phone Number length must be equal to 10',
    otpNotReceivedMessage: `Didn't got OTP. Resend in ? sec`,
    or: 'Or',
    countryCode: '+91',
    getOtp: 'Get OTP',
    enterOTP: 'Enter OTP',
    resendOtp: 'Resend OTP',
    submit: 'Submit',
    createNewPassword: 'Create New Password',
    enterNewPassword: 'Enter New Password',
    confirmNewPassword: 'Confirm New Password'
  },
  loginDialog: {
    signIn: 'Sign In',
    newUser: 'New User?',
    emailOrPhone: 'Email Address or Phone Number',
    password: 'Password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot Password?',
    or: 'Or',
    wrongCriteria: 'Wrong username or password',
    didNotHaveAnAccount: "Didn't have an account?",
    withGoogle: 'Continue With Google',
    withFacebook: 'Continue With Facebook',
    notice: `By clicking Sign in or Continue with Google, or Facebook you agree to our Terms of Use and Privacy Policy. We may send you communications. We'll never post without your permission.`
  },
  listTable: {
    noData: 'No Data'
  },
  categoryDropdown: {
    none: 'None'
  },
  productCommon: {
    basic: 'Basic',
    name: 'Name',
    commonName: 'Common Name',
    seller: 'Seller',
    description: 'Description',
    tag: 'Tag',
    selectCategory: 'Select Category',
    category: 'Category',
    tags: 'Tags',
    add: 'Add',
    addMore: 'Add More',
    addValue: 'Add Value',
    removeUnit: 'Remove Unit',
    addSpecs: 'Add Specification',
    removeSpec: 'Remove Specification',
    removeValue: 'Remove Value',
    removeOption: 'Remove Option',
    locationTags: 'Location Tags',
    locationTag: 'Location Tag',
    productOptions: 'Product Options',
    option: 'Option',
    uploadImages: 'Upload Images',
    addImages: 'Add Image',
    value: 'Value',
    addOptions: '+ Add Options',
    skuUnit: 'Stock Keeping Unit',
    addUnit: '+ Add Unit',
    quantityInStock: 'Quantity in Stock',
    quantity: 'Quantity',
    code: 'Code',
    pricePerUnit: 'Price per Unit',
    sellingPricePerUnit: 'Selling Price',
    product: 'Product',
    stocks: 'Stocks',
    images: 'Images',
    saveAndContinue: 'Save and Continue',
    nameIsRequired: 'Name is Required',
    commonNameIsRequired: 'Common Name is Required',
    categoryIsRequired: 'Category is Required',
    edit: 'Edit',
    productDescription: 'Product Description'
  },
  seller: {
    product: {
      name: 'Name',
      commonName: 'Common Name',
      description: 'Description',
      category: 'Category',
      tags: 'Tags',
      locationTags: 'Location Tags',
      enabled: 'Enabled'
    },
    profile: {
      sellerName: 'Seller Name',
      storeName: 'Store Name',
      description: 'Description',
      dateOfBirth: 'Date of Birth',
      basicDetails: 'Basic Details',
      storeAddress: 'Store Address',
      emailAddress: 'Email Address',
      phoneNumber: 'Phone Number',
      addresssLine1: 'Address Line 1',
      addresssLine2: 'Address Line 2',
      addresssLine3: 'Address Line 3',
      landmark: 'Landmark',
      city: 'City',
      pinCode: 'Pin Code',
      state: 'State',
      additionalDetails: 'Additional Details',
      shippingOptions: 'Shipping Options',
      gstDetails: 'GST Details',
      gstNumber: 'GST Number',
      bankingDetails: 'Banking Details',
      panNumber: 'PAN Number',
      aadharNumber: 'Aadhar Number',
      bankAccountNumber: 'Bank Account Number',
      ifscCode: 'IFSC Code',
      edit: 'Edit',
      save: 'Save',
      cancel: 'Cancel'
    },
    header: {
      dashboard: 'Dashboard',
      profile: 'Profile',
      products: 'Products',
      orders: 'Orders',
      reviews: 'Product Reviews',
      signOut: 'Sign Out',
      home: 'Back to Crapla'
    }
  }
};

export default resource;
